---
- name: 'Ensure Ansible from PyPi'
  community.general.pipx:
    name: "{{ ansible_controller_ansible_pkg }}"
    state: 'present'
  when: ansible_controller_ansible_from_pip
  environment: "{{ proxy_env }}"
  become: false

- name: 'Ensure Ansible from PyPi'
  community.general.pipx:
    name: "{{ ansible_controller_ansible_pkg }}"
    inject_packages:
      - 'ansible-merge-vars'
      - 'ara'
      - 'passlib'
      - 'dnspython'
    state: 'inject'
  when: ansible_controller_ansible_from_pip
  environment: "{{ proxy_env }}"
  become: false
