---
- name: 'Ensure Ansible from PyPi'
  ansible.builtin.pip:
    name: "{{ ansible_controller_ansible_pkg }}"
    state: 'present'
    umask: "0022"
    executable: "{{ ansible_controller_pip_exe | default(omit, true) }}"
  when: ansible_controller_ansible_from_pip
  environment: "{{ ansible_controller_env }}"

- name: 'Ensure extra PiPy tools'
  ansible.builtin.pip:
    name:
      - 'ansible-merge-vars'
      - 'ara'
    state: 'present'
    umask: "0022"
    executable: "{{ ansible_controller_pip_exe | default(omit, true) }}"
  environment: "{{ ansible_controller_env }}"

- name: 'Install remaining supporting tools from PyPi (RHEL)'
  ansible.builtin.pip:
    name:
      - 'passlib'
    state: 'present'
    umask: "0022"
    executable: "{{ ansible_controller_pip_exe | default(omit, true) }}"
  when:
    - ansible_facts['os_family'] == 'RedHat'
  environment: "{{ ansible_controller_env }}"
