---
- name: 'Include OS specific vars'
  ansible.builtin.include_vars: "{{ lookup('first_found', role_vars_files) }}"
  vars:
    role_vars_files:
      files:
        - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
      paths:
        - 'vars'

- name: 'Set environment facts (placeholder)'
  ansible.builtin.set_fact:
    ansible_controller_env:
      empty_var: 'Just_a_placeholder'
      PATH: "~/.local/bin:{{ ansible_facts['env']['PATH'] }}"  # Add pipx path

- name: 'Set environment facts (http_proxy)'
  ansible.builtin.set_fact:
    ansible_controller_env:
      http_proxy: "{{ http_proxy_url }}"
      https_proxy: "{{ http_proxy_url }}"
      PATH: "~/.local/bin:{{ ansible_facts['env']['PATH'] }}"  # Add pipx path
  when: http_proxy_url is defined

- name: 'Ensure supporting tools'
  ansible.builtin.package:
    name:
      - 'git'
      - 'jq'
      - 'unzip'
      - "{{ ansible_controller_pinentry_package }}"
      - "{{ ansible_controller_pip_package }}"
    state: 'present'

- name: 'Ensure supporting tools'
  ansible.builtin.package:
    name: "{{ ansible_controller_pwgen_package }}"
    disable_gpg_check: "{{ ansible_controller_pwgen_gpgcheck }}"
    state: 'present'
  when: ansible_facts['os_family'] == 'RedHat'

- name: 'Ensure supporting tools'
  ansible.builtin.package:
    name: "{{ ansible_controller_pwgen_package }}"
    state: 'present'
  when: ansible_facts['os_family'] == 'Debian'

- name: 'Ensure directories'
  ansible.builtin.file:
    path: "{{ dir }}"
    state: 'directory'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0750'
  loop:
    - '/opt/ansible'
    - '/opt/ansible/projects/'
    - '/opt/ansible/resources/'
    - '/opt/ansible/tools/'
    - '/opt/ansible/vaults/'
  loop_control:
    loop_var: 'dir'

- name: 'Set up tool chain'
  become: false
  environment: "{{ ansible_controller_env }}"
  block:
    - name: 'Install PipX'
      ansible.builtin.pip:
        name: 'pipx'
        executable: "pip{{ ansible_controller_python_version }}"
        extra_args: '--user'
        state: 'present'
      when: ansible_facts['os_family'] == 'RedHat'

    - name: 'Ensure Ansible utils repo'
      ansible.builtin.git:
        repo: "{{ ansible_controller_utils_repo }}"
        dest: '/opt/ansible/tools/ansible-utils'
        version: 'master'
        force: true
        umask: '0022'
      environment: "{{ ansible_controller_env }}"

    - name: 'Ensure dir symlinks in Ansible Runner home'
      ansible.builtin.file:
        src: "/opt/ansible/{{ dir_link }}"
        dest: "~/{{ dir_link }}"
        state: 'link'
      loop:
        - 'projects'
        - 'resources'
      loop_control:
        loop_var: 'dir_link'

    - name: 'Ensure retrieve_vault.sh'
      ansible.builtin.copy:
        src: '/opt/ansible/tools/ansible-utils/retrieve_vault.sh'
        dest: '/opt/ansible/vaults/retrieve_vault.sh'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0775'
        remote_src: true

    - name: 'Ensure gpgkey cronjob'
      ansible.builtin.cron:
        name: 'Hourly GPG key check'
        minute: '0'
        user: "{{ ansible_user }}"
        job: '/usr/local/bin/gpgkey -c'

    - name: 'Ensure Bitwarden CLI tool'
      ansible.builtin.unarchive:
        src: 'https://vault.bitwarden.com/download/?app=cli&platform=linux'
        remote_src: true
        dest: '/usr/local/bin'
        owner: 'root'
        group: 'root'
        mode: '0755'
      when: ansible_controller_utils_bitwarden | bool

    - name: 'Ensure Bitwarden extra CA certificates'
      ansible.builtin.copy:
        content: |
          # This file is managed by Ansible, YOUR CHANGES WILL BE LOST!
          export NODE_EXTRA_CA_CERTS={{ ansible_controller_bitwarden_extra_ca }}
        dest: '/etc/profile.d/node_extra_ca.sh'
        owner: 'root'
        group: 'root'
        mode: '0644'
      when: ansible_controller_bitwarden_extra_ca | length > 0

    - name: 'Ensure directories'
      ansible.builtin.file:
        path: "~/.gnupg/"
        state: 'directory'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'

    - name: 'Ensure GPG agent settings'
      ansible.builtin.template:
        src: 'gpg-agent.conf.j2'
        dest: "~/.gnupg/gpg-agent.conf"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0640'

    - name: 'Ensure shell settings'
      ansible.builtin.blockinfile:
        path: "~/.bashrc"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        marker: '# {mark} ANSIBLE-CONTROLLER ROLE MANAGED BLOCK'
        block: "{{ lookup('file', 'bashrc') }}"

    - name: 'Install Ansible version with PipX'
      ansible.builtin.command:
        cmd: "/opt/ansible/tools/ansible-utils/pipx_ansible {{ ansible_controller_version }}"
        creates: "~/.local/share/pipx/venvs/ansible-core-{{ ansible_controller_version | replace('.', '-') }}"
      loop: "{{ ansible_controller_versions }}"
      loop_control:
        loop_var: 'ansible_controller_version'

- name: 'Ensure tool symlinks'
  ansible.builtin.file:
    src: "/opt/ansible/tools/ansible-utils/{{ tool_link }}"
    dest: "/usr/local/bin/{{ tool_link }}"
    state: 'link'
  loop:
    - 'encryptansible'
    - 'runansible'
    - 'showansible'
    - 'gpgkey'
    - 'pipx_ansible'
  loop_control:
    loop_var: 'tool_link'

- name: 'Check linger for useraccount'
  ansible.builtin.command: loginctl show-user {{ ansible_user }} -p Linger
  register: 'ansible_controller_linger'
  changed_when: false
  when: not _ansible_controller_molecule | default(false) | bool

- name: 'Ensure linger enabled for useraccount'
  ansible.builtin.command: loginctl enable-linger {{ ansible_user }}
  when:
    - not _ansible_controller_molecule | default(false) | bool
    - "'Linger=no' in ansible_controller_linger['stdout']"
  changed_when: true

- name: 'Configure for GPG agent debug logging'
  when: ansible_controller_gpg_debug
  block:
    - name: 'Configure log file'
      ansible.builtin.file:
        path: '/var/log/ansible-gpg-agent.log'
        owner: 'ansible'
        group: 'ansible'
        mode: '0640'
        state: 'touch'

    - name: 'Configure logrotate for GPG debug log'
      ansible.builtin.copy:
        src: 'ansible-gpg-agent'
        dest: '/etc/logrotate.d/ansible-gpg-agent'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify: 'Restart logrotate'
