---
- name: 'Configure APT Ansible repo key'
  ansible.builtin.uri:
    url: "{{ deb_ansible_controller_repo_key }}"
    dest: '/etc/apt/keyrings/ansible.asc'
    status_code:
      - 200
      - 304
  environment:
    http_proxy: "{{ apt_proxy_url | default(omit) }}"
    https_proxy: "{{ apt_proxy_url | default(omit) }}"

- name: 'Configure other repos'
  ansible.builtin.copy:
    content: |
      # This file is managed by Ansible.
      # YOUR CHANGES WILL BE LOST!
      Types: deb
      URIs: {{ deb_ansible_controller_repo }}
      Suites: {{ deb_ansible_controller_repo_suite }}
      Components: {{ deb_ansible_controller_repo_components }}
      Signed-By: /etc/apt/keyrings/ansible.asc
    dest: '/etc/apt/sources.list.d/ansible.sources'
    owner: 'root'
    group: 'root'
    mode: '0644'
