---
- name: 'Ensure Ansible signing key'
  ansible.builtin.apt_key:
    url: "{{ deb_ansible_controller_repo_key }}"

- name: 'Ensure Ansible repository'
  ansible.builtin.apt_repository:
    repo: "{{ deb_ansible_controller_repo }}"
    state: 'present'
    filename: 'ansible'
