---
- name: 'Converge'
  hosts: 'all'
  vars:
    ansible_user: 'root'  # Molecule does not provide this variable, where Ansible normally does
    _ansible_controller_molecule: true  # Systemd is not fully running. so we cannot check linger
  tasks:
    - name: 'Run role'
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
