---
- name: 'Update package sources'
  hosts: 'all'
  tasks:
    - name: 'Install cron'
      ansible.builtin.apt:
        name: 'cron'
        state: 'present'
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: 'Install cron'
      ansible.builtin.dnf:
        name: 'cronie'
        state: 'present'
        update_cache: true
      when: ansible_facts['os_family'] == 'RedHat'
