---
- name: 'Update package sources'
  hosts: 'all'
  tasks:
    - name: 'Prepare Debian'
      block:
        - name: 'Update APT cache'
          ansible.builtin.apt:
            update_cache: true
          when: ansible_facts['os_family'] == 'Debian'
        - name: 'Install cron'
          ansible.builtin.apt:
            name: 'cron'
            state: 'present'

    - name: 'Update YUM cache'
      ansible.builtin.yum:
        update_cache: true
      when: ansible_facts['os_family'] == 'RedHat'
